package:
  name: ruby
  version: 2.0.0

source:
  fn: ruby-2.0.0-p598.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p598.tar.gz
  sha256: bb5be55cd1f49c95bb05b6f587701376b53d310eb1bb7c76fbd445a1c75b51e8

test:
  commands:
    - ruby --version

requirements:
  build:
    - openssl
    - zlib

about:
  home: http://www.ruby-lang.org
  license: BSD
