package:
  name: ruby
  version: 2.1.5

source:
  fn: ruby-2.0.0-p598.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.5.tar.gz
  sha256: 4305cc6ceb094df55210d83548dcbeb5117d74eea25196a9b14fa268d354b100

test:
  commands:
    - ruby --version

requirements:
  build:
    - openssl
    - zlib

about:
  home: http://www.ruby-lang.org
  license: BSD
