package:
  name: ruby
  version: 2.0.0

source:
  fn: ruby-2.0.0-p598.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p598.tar.gz
  sha256: 4136bf7d764cbcc1c7da2824ed2826c3550f2b62af673c79ddbf9049b12095fd

test:
  commands:
    - ruby --version

requirements:
  build:
    - openssl
    - zlib

about:
  home: http://www.ruby-lang.org
  license: BSD
