package:
  name: ruby
  version: 2.2.0

source:
  fn: ruby-2.2.0.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.0.tar.gz
  sha256: 7671e394abfb5d262fbcd3b27a71bf78737c7e9347fa21c39e58b0bb9c4840fc

test:
  commands:
    - ruby --version

requirements:
  build:
    - openssl
    - zlib

about:
  home: http://www.ruby-lang.org
  license: BSD
